# Config file

# PROJECT
PROJECT: 'runs\train\exp'
NAME: 'EffNetB3_BatchSize48_ImageSize128_CutOut_LabelSmoothing_DropOut0.2' 

# AUGMENTATION PARAMS
TRANSFORMS:
  ARGS:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    image_size: [128, 128]

# TRAINER
TRAINER:
  GPU: [0]
  MIN_EPOCHS: 1
  MAX_EPOCHS: 300
  CHECK_VAL_EVERY_N_EPOCH: 1
  SHOW_PROGRESS_BAR: True

# MODEL
MODEL:
  NAME: 'resnet18'
  PRETRAINED: 
    ENABLE: False
    WEIGHTS: ''
    STRICT_LOAD: False

# TRAIN
TRAIN:
  DATASET:
    ARGS:
      imgs_path: 'data/downloaded_data/'
      anno_path: 'data/annotation/data.xlsx'
      is_train: True

  DATALOADER:
    ARGS:
      batch_size: 48
      shuffle: True
      drop_last: True
      num_workers: 4
      pin_memory: True

# VALIDATION
VAL:
  DATASET:
    ARGS:
      imgs_path: 'data/downloaded_data/'
      anno_path: 'data/annotation/data.xlsx'
      is_train: False

  DATALOADER:
    ARGS:
      batch_size: 48
      shuffle: False
      drop_last: False
      num_workers: 4
      pin_memory: True

# OPTIMIZER
OPTIMIZER:
  NAME: 'AdamW'
  ARGS:
    lr: 1.0e-3
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 1.0e-5
    amsgrad: False

# SCHEDULER
SCHEDULER:
  NAME: 'CyclicLR'
  ARGS: 
    base_lr: 1.0e-5
    max_lr: 1.0e-3
    step_size_up: 5
    step_size_down: 15
    mode: 'exp_range'
    gamma: 0.9
    scale_mode: 'cycle'
    cycle_momentum: False
    base_momentum: 0.8
    max_momentum: 0.99
    last_epoch: -1

# SCHEDULER:
#   NAME: 'CosineAnnealingLR'
#   ARGS: 
#     T_max: 30
#     eta_min: 1.0e-5
#     last_epoch: -1


# CHECKPOINTS
CHECKPOINTS:
  ARGS:
    save_weights_only: True
    verbose: True
    monitor: 'val_loss'
    period: 1
    mode: 'min'
    prefix: ''

# CUDNN
CUDNN:
  BENCHMARK: False
  DETERMINISTIC: False

# REPRODUCIBILITY
REPRODUCIBILITY:
  ENABLE: True
  TORCH_SEED: 42
  NUMPY_SEED: 42